name: Desplegar Blog Astro

on:
  push:
    branches: [ main, master ] # Se activa tanto si tu rama se llama main o master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar proyecto Astro
        run: npm run build

      # Este es el truco para solucionar el error del dominio duplicado
      - name: Inyectar CNAME institucional
        run: echo "culturaydesarrollo.org" > ./dist/CNAME

      - name: Subir artefacto para Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
